# This code is a Qiskit project.
#
# (C) Copyright IBM 2023.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Lint
on: [pull_request, merge_group]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Qiskit'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Node.js dependencies
        run: npm ci

      - name: File metadata
        run: npm run check:metadata
      - name: Spellcheck
        run: npm run check:spelling
      - name: Link checker
        run: npm run check:links
      - name: Release notes
        run: npm run check:release-notes
      - name: Formatting
        run: npm run check:fmt
      - name: Typecheck
        run: npm run typecheck
      - name: Run infrastructure tests
        run: npm test
